package entities;
// Generated Jun 29, 2018 4:24:12 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.map.Module;
import org.codehaus.jackson.map.ObjectMapper;

/**
 * Element generated by hbm2java
 */
@Entity
@Table(name = "element")
public class Element implements java.io.Serializable {
	
	private int id;
	private ElementType elementType;
	private Entiti entiti;
	private String idelement;
	private String label;
	private Boolean isRequired;
	private Boolean isUnique;
	private String pattern;
	private String patternMessage;
	private int orderElement;
	private Boolean isCreate;
	private Boolean isUpdate;
	private Boolean isDelete;
	private Date createdAt;
	private Date updatedAt;

	public Element() {
	}

	public Element(int id, ElementType elementType, Entiti entiti, String idelement, String label, int orderElement) {
		this.id = id;
		this.elementType = elementType;
		this.entiti = entiti;
		this.idelement = idelement;
		this.label = label;
		this.orderElement = orderElement;
	}

	public Element(int id, ElementType elementType, Entiti entiti, String idelement, String label, Boolean isRequired,
			Boolean isUnique, String pattern, String patternMessage, int orderElement, Boolean isCreate,
			Boolean isUpdate, Boolean isDelete, Date createdAt, Date updatedAt) {
		this.id = id;
		this.elementType = elementType;
		this.entiti = entiti;
		this.idelement = idelement;
		this.label = label;
		this.isRequired = isRequired;
		this.isUnique = isUnique;
		this.pattern = pattern;
		this.patternMessage = patternMessage;
		this.orderElement = orderElement;
		this.isCreate = isCreate;
		this.isUpdate = isUpdate;
		this.isDelete = isDelete;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}
	
	public Element(Object element) {
		try{
			ObjectMapper mapper = new ObjectMapper();
			String jsonInString = mapper.writeValueAsString(element);
			Element _element = mapper.readValue(jsonInString, Element.class);
			this.id = _element.id;
			this.elementType = _element.elementType;
			this.entiti = _element.entiti;
			this.idelement = _element.idelement;
			this.label = _element.label;
			this.isRequired = _element.isRequired;
			this.isUnique = _element.isUnique;
			this.pattern = _element.pattern;
			this.patternMessage = _element.patternMessage;
			this.orderElement = _element.orderElement;
			this.isCreate = _element.isCreate;
			this.isUpdate = _element.isUpdate;
			this.isDelete = _element.isDelete;
			this.createdAt = _element.createdAt;
			this.updatedAt = _element.updatedAt;
		}catch(Exception exception){
			System.out.println("error to cast element "+exception.getMessage());
		}	
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "elementType", nullable = false)
	public ElementType getElementType() {
		return this.elementType;
	}

	public void setElementType(ElementType elementType) {
		elementType.setElements(null);
		this.elementType = elementType;
	}
	
	public void setElementType(Object elementType) {
		ElementType _elementType =(ElementType) elementType;
		_elementType.setElements(null);
		this.elementType = _elementType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "entiti", nullable = false)
	public Entiti getEntiti() {
		return this.entiti;
	}

	public void setEntiti(Entiti entiti) {
		entiti.setElements(null);
		this.entiti = entiti;
	}
	
	public void setEntiti(Object entiti) {
		try{
			if (entiti instanceof Entiti){
				Entiti newEntiti = (Entiti) entiti;
				newEntiti.setElements(null);
				this.entiti=newEntiti;
			}else{
				ObjectMapper objectMapper = new ObjectMapper();
				String jsonInString = objectMapper.writeValueAsString(entiti);
				Entiti newElement = objectMapper.readValue(jsonInString, Entiti.class);
				newElement.setElements(null);
				this.entiti = newElement;	
			}	
		}catch(Exception exception){
			System.out.println("error to set entiti in element, api project "+exception.getMessage());
		}
		
		
	}

	@Column(name = "idelement", nullable = false, length = 50)
	public String getIdelement() {
		return this.idelement;
	}

	public void setIdelement(String idelement) {
		this.idelement = idelement;
	}

	@Column(name = "label", nullable = false, length = 100)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "isRequired")
	public Boolean getIsRequired() {
		return this.isRequired;
	}

	public void setIsRequired(Boolean isRequired) {
		this.isRequired = isRequired;
	}

	@Column(name = "isUnique")
	public Boolean getIsUnique() {
		return this.isUnique;
	}

	public void setIsUnique(Boolean isUnique) {
		this.isUnique = isUnique;
	}

	@Column(name = "pattern", length = 300)
	public String getPattern() {
		return this.pattern;
	}

	public void setPattern(String pattern) {
		this.pattern = pattern;
	}

	@Column(name = "patternMessage", length = 150)
	public String getPatternMessage() {
		return this.patternMessage;
	}

	public void setPatternMessage(String patternMessage) {
		this.patternMessage = patternMessage;
	}

	@Column(name = "orderElement", nullable = false)
	public int getOrderElement() {
		return this.orderElement;
	}

	public void setOrderElement(int orderElement) {
		this.orderElement = orderElement;
	}

	@Column(name = "isCreate")
	public Boolean getIsCreate() {
		return this.isCreate;
	}

	public void setIsCreate(Boolean isCreate) {
		this.isCreate = isCreate;
	}

	@Column(name = "isUpdate")
	public Boolean getIsUpdate() {
		return this.isUpdate;
	}

	public void setIsUpdate(Boolean isUpdate) {
		this.isUpdate = isUpdate;
	}

	@Column(name = "isDelete")
	public Boolean getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 23)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
