package entities;
// Generated Jun 26, 2018 9:30:40 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Element generated by hbm2java
 */
@Entity
@Table(name = "element")
public class Element implements java.io.Serializable {

	private int id;
	private ElementType elementType;
	private Entiti entiti;
	private String idelement;
	private String label;
	private Boolean isRequired;
	private Boolean isUnique;
	private String pattern;
	private String patternMessage;
	private int orderElement;
	private Boolean isCreate;
	private Boolean isUpdate;
	private Boolean isDelete;
	private Date createdAt;
	private Date updatedAt;

	public Element() {
	}

	public Element(int id, ElementType elementType, Entiti entiti, String idelement, String label, int orderElement) {
		this.id = id;
		this.elementType = elementType;
		this.entiti = entiti;
		this.idelement = idelement;
		this.label = label;
		this.orderElement = orderElement;
	}

	public Element(int id, ElementType elementType, Entiti entiti, String idelement, String label, Boolean isRequired,
			Boolean isUnique, String pattern, String patternMessage, int orderElement, Boolean isCreate,
			Boolean isUpdate, Boolean isDelete, Date createdAt, Date updatedAt) {
		this.id = id;
		this.elementType = elementType;
		this.entiti = entiti;
		this.idelement = idelement;
		this.label = label;
		this.isRequired = isRequired;
		this.isUnique = isUnique;
		this.pattern = pattern;
		this.patternMessage = patternMessage;
		this.orderElement = orderElement;
		this.isCreate = isCreate;
		this.isUpdate = isUpdate;
		this.isDelete = isDelete;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "elementTypeId", nullable = false)
	public ElementType getElementType() {
		return this.elementType;
	}

	public void setElementType(ElementType elementType) {
		elementType.setElements(null);
		this.elementType = elementType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "entitiId", nullable = false)
	public Entiti getEntiti() {
		return this.entiti;
	}

	public void setEntiti(Entiti entiti) {
		entiti.setElements(null);
		this.entiti = entiti;
	}

	@Column(name = "idelement", nullable = false, length = 50)
	public String getIdelement() {
		return this.idelement;
	}

	public void setIdelement(String idelement) {
		this.idelement = idelement;
	}

	@Column(name = "label", nullable = false, length = 100)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "isRequired")
	public Boolean getIsRequired() {
		return this.isRequired;
	}

	public void setIsRequired(Boolean isRequired) {
		this.isRequired = isRequired;
	}

	@Column(name = "isUnique")
	public Boolean getIsUnique() {
		return this.isUnique;
	}

	public void setIsUnique(Boolean isUnique) {
		this.isUnique = isUnique;
	}

	@Column(name = "pattern", length = 100)
	public String getPattern() {
		return this.pattern;
	}

	public void setPattern(String pattern) {
		this.pattern = pattern;
	}

	@Column(name = "patternMessage", length = 150)
	public String getPatternMessage() {
		return this.patternMessage;
	}

	public void setPatternMessage(String patternMessage) {
		this.patternMessage = patternMessage;
	}

	@Column(name = "orderElement", nullable = false)
	public int getOrderElement() {
		return this.orderElement;
	}

	public void setOrderElement(int orderElement) {
		this.orderElement = orderElement;
	}

	@Column(name = "isCreate")
	public Boolean getIsCreate() {
		return this.isCreate;
	}

	public void setIsCreate(Boolean isCreate) {
		this.isCreate = isCreate;
	}

	@Column(name = "isUpdate")
	public Boolean getIsUpdate() {
		return this.isUpdate;
	}

	public void setIsUpdate(Boolean isUpdate) {
		this.isUpdate = isUpdate;
	}

	@Column(name = "isDelete")
	public Boolean getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 23)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
