package entities;
// Generated Jun 30, 2018 7:41:07 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Form generated by hbm2java
 */
@Entity
@Table(name = "form")
public class Form implements java.io.Serializable {

	private int id;
	private Module module;
	private String name;
	private String title;
	private String url;
	private int users;
	private String icon;
	private Integer orderElement;
	private Date createdAt;
	private Date updatedAt;
	private Set<RolesForm> rolesForms = new HashSet<RolesForm>(0);

	public Form() {
	}

	public Form(int id, Module module, String name, String title, String url, int users) {
		this.id = id;
		this.module = module;
		this.name = name;
		this.title = title;
		this.url = url;
		this.users = users;
	}

	public Form(int id, Module module, String name, String title, String url, int users, String icon,
			Integer orderElement, Date createdAt, Date updatedAt, Set<RolesForm> rolesForms) {
		this.id = id;
		this.module = module;
		this.name = name;
		this.title = title;
		this.url = url;
		this.users = users;
		this.icon = icon;
		this.orderElement = orderElement;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.rolesForms = rolesForms;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "module", nullable = false)
	public Module getModule() {
		return this.module;
	}

	public void setModule(Module module) {
		module.setForms(null);
		this.module = module;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "title", nullable = false, length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "url", nullable = false, length = 100)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "users", nullable = false)
	public int getUsers() {
		return this.users;
	}

	public void setUsers(int users) {
		this.users = users;
	}

	@Column(name = "icon", length = 20)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "orderElement")
	public Integer getOrderElement() {
		return this.orderElement;
	}

	public void setOrderElement(Integer orderElement) {
		this.orderElement = orderElement;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 23)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "form")
	public Set<RolesForm> getRolesForms() {
		return this.rolesForms;
	}

	public void setRolesForms(Set<RolesForm> rolesForms) {
		this.rolesForms = rolesForms;
	}

}
