package entities;
// Generated Jul 1, 2018 8:12:33 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name = "module")
public class Module implements java.io.Serializable {

	private int id;
	private String name;
	private int users;
	private Date createdAt;
	private Date updatedAt;
	private String icon;
	private int orderElement;
	private Set<Form> forms = new HashSet<Form>(0);

	public Module() {
	}

	public Module(int id, String name, int users) {
		this.id = id;
		this.name = name;
		this.users = users;
	}

	public Module(int id, String name, int users, Date createdAt, Date updatedAt, String icon, int orderElement,
			Set<Form> forms) {
		this.id = id;
		this.name = name;
		this.users = users;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.icon = icon;
		this.orderElement = orderElement;
		this.forms = forms;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "users", nullable = false)
	public int getUsers() {
		return this.users;
	}

	public void setUsers(int users) {
		this.users = users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 23)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "icon", length = 50)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "orderElement")
	public int getOrderElement() {
		return this.orderElement;
	}

	public void setOrderElement(int orderElement) {
		this.orderElement = orderElement;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	public Set<Form> getForms() {
		return this.forms;
	}

	public void setForms(Set<Form> forms) {
		this.forms = forms;
	}

}
