package entities;
// Generated Jun 22, 2018 2:03:49 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student")
public class Student implements java.io.Serializable {

	private int id;
	private String firstName;
	private String lastName;
	private String carne;
	private Date createdAt;
	private Date updatedAt;
	private Set<QuizDetail> quizDetails = new HashSet<QuizDetail>(0);

	public Student() {
	}

	public Student(int id, String firstName, String lastName, String carne) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.carne = carne;
	}

	public Student(int id, String firstName, String lastName, String carne, Date createdAt, Date updatedAt,
			Set<QuizDetail> quizDetails) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.carne = carne;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.quizDetails = quizDetails;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "firstName", nullable = false, length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", nullable = false, length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "carne", nullable = false, length = 50)
	public String getCarne() {
		return this.carne;
	}

	public void setCarne(String carne) {
		this.carne = carne;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 23)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	public Set<QuizDetail> getQuizDetails() {
		return this.quizDetails;
	}

	public void setQuizDetails(Set<QuizDetail> quizDetails) {
		this.quizDetails = quizDetails;
	}

}
