package entities;
// Generated Jun 26, 2018 5:31:58 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users")
public class Users implements java.io.Serializable {

	private int id;
	private Roles roles;
	private String name;
	private String email;
	private String password;
	private Boolean isEnabled;
	private int users;
	private Date createdAt;
	private Date updatedAt;

	public Users() {
	}

	public Users(int id, Roles roles, String name, String email, String password, int users) {
		this.id = id;
		this.roles = roles;
		this.name = name;
		this.email = email;
		this.password = password;
		this.users = users;
	}

	public Users(int id, Roles roles, String name, String email, String password, Boolean isEnabled, int users,
			Date createdAt, Date updatedAt) {
		this.id = id;
		this.roles = roles;
		this.name = name;
		this.email = email;
		this.password = password;
		this.isEnabled = isEnabled;
		this.users = users;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roles", nullable = false)
	public Roles getRoles() {
		return this.roles;
	}

	
	public void setRoles(Roles roles) {
		roles.setUserses(null);
		this.roles = roles;
	}
	
	public void setRoles(Object roles) {
		this.roles =  (Roles) roles;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "isEnabled")
	public Boolean getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

	@Column(name = "users", nullable = false)
	public int getUsers() {
		return this.users;
	}

	public void setUsers(int users) {
		this.users = users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 23)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
