package com.student.entities;
// Generated Jun 20, 2018 1:22:39 PM by Hibernate Tools 5.1.0.Alpha1

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Locale;
 
/**
 * Element generated by hbm2java
 */
 
public class Element implements java.io.Serializable {
	DateFormat format = new SimpleDateFormat("dd/mm/yyyy", Locale.ENGLISH);
	private int id;
	private ElementType elementType;
	private Entiti entiti;
	private String idelement;
	private String label;
	private Boolean isRequired;
	private Boolean isUnique;
	private String pattern;
	private String patternMessage;
	private int orderElement;
	private Boolean isCreate;
	private Boolean isUpdate;
	private Boolean isDelete;
	private Date createdAt;
	private Date updatedAt;

	public Element() {
	}

	public Element(Object object){
		LinkedHashMap objectMap = (LinkedHashMap)object;
		this.id = (int) objectMap.get("id");
		try{
			this.elementType = new ElementType(objectMap.get("elementType"));	
		}catch(Exception exception){
			System.out.println("Error to convert elementType");
		}
		try{
			this.entiti = (Entiti) objectMap.get("entiti");
		}catch(Exception exception){
			System.out.println("Error to convert entiti");
		}
		this.idelement = (String) objectMap.get("idelement");
		this.label = (String) objectMap.get("label");
		this.orderElement = (int) objectMap.get("orderElement");
		this.isRequired = (Boolean) objectMap.get("isRequired");
		this.isUnique = (Boolean) objectMap.get("isUnique");
		this.pattern = (String) objectMap.get("pattern");
		this.patternMessage = (String) objectMap.get("patternMessage");
		
		this.setIsCreate((Boolean) objectMap.get("isCreate"));
		this.setIsUpdate((Boolean) objectMap.get("isUpdate"));
		this.setIsDelete((Boolean) objectMap.get("isDelete"));
		
		if (objectMap.get("createdAt")==null){
			this.createdAt=null;	
		}else{
			try{
				this.createdAt= (Date) format.parse(objectMap.get("createdAt").toString());	
			}catch(Exception exception){
				System.out.println("Error to convert createdAt");
			}
			
		}
		
		if (objectMap.get("updatedAt")==null){
			this.updatedAt=null;	
		}else{
			try{
				this.updatedAt= (Date) format.parse(objectMap.get("createdAt").toString());
			}catch(Exception exception){
				System.out.println("Error to convert updatedAt");
			}
		}
	}
	
	public Element(int id, ElementType elementType, Entiti entiti, String idelement, String label, int orderElement) {
		this.id = id;
		this.elementType = elementType;
		this.entiti = entiti;
		this.idelement = idelement;
		this.label = label;
		this.orderElement = orderElement;
	}

	public Element(int id, ElementType elementType, Entiti entiti, String idelement, String label, Boolean isRequired,
			Boolean isUnique, String pattern, String patternMessage, int orderElement,Boolean isCreate,
			Boolean isUpdate, Boolean isDelete,  Date createdAt, Date updatedAt) {
		this.id = id;
		this.elementType = elementType;
		this.entiti = entiti;
		this.idelement = idelement;
		this.label = label;
		this.isRequired = isRequired;
		this.isUnique = isUnique;
		this.pattern = pattern;
		this.patternMessage = patternMessage;
		this.orderElement = orderElement;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.setIsCreate(isCreate);
		this.setIsUpdate(isUpdate);
	}

 
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

 
	public ElementType getElementType() {
		return this.elementType;
	}

	public void setElementType(ElementType elementType) {
		elementType.setElements(null);
		this.elementType = elementType;
	}

 
	public Entiti getEntiti() {
		return this.entiti;
	}

	public void setEntiti(Entiti entiti) {
		this.entiti = entiti;
	}

	 
	public String getIdelement() {
		return this.idelement;
	}

	public void setIdelement(String idelement) {
		this.idelement = idelement;
	}

	 
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	 
	public Boolean getIsRequired() {
		return this.isRequired;
	}

	public void setIsRequired(Boolean isRequired) {
		this.isRequired = isRequired;
	}

	 
	public Boolean getIsUnique() {
		return this.isUnique;
	}

	public void setIsUnique(Boolean isUnique) {
		this.isUnique = isUnique;
	}

	 
	public String getPattern() {
		return this.pattern;
	}

	public void setPattern(String pattern) {
		this.pattern = pattern;
	}

	 
	public String getPatternMessage() {
		return this.patternMessage;
	}

	public void setPatternMessage(String patternMessage) {
		this.patternMessage = patternMessage;
	}

	 
	public int getOrderElement() {
		return this.orderElement;
	}

	public void setOrderElement(int orderElement) {
		this.orderElement = orderElement;
	}

	 
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

 
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Boolean getIsCreate() {
		return isCreate;
	}

	public void setIsCreate(Boolean isCreate) {
		this.isCreate = isCreate;
	}

	public Boolean getIsUpdate() {
		return isUpdate;
	}

	public void setIsUpdate(Boolean isUpdate) {
		this.isUpdate = isUpdate;
	}

	public Boolean getIsDelete() {
		return isDelete;
	}

	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

}
