package com.student.entities;
// Generated Jun 26, 2018 4:22:06 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
/**
 * Form generated by hbm2java
 */
public class Form implements java.io.Serializable {

	private int id;
	private String name;
	private String url;
	private Date createdAt;
	private Date updatedAt;
	private Set<RolesForm> rolesForms = new HashSet<RolesForm>(0);

	public Form() {
	}

	public Form(int id, String name, String url) {
		this.id = id;
		this.name = name;
		this.url = url;
	}

	public Form(int id, String name, String url, Date createdAt, Date updatedAt, Set<RolesForm> rolesForms) {
		this.id = id;
		this.name = name;
		this.url = url;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.rolesForms = rolesForms;
	}

	
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}


	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set<RolesForm> getRolesForms() {
		return this.rolesForms;
	}

	public void setRolesForms(Set<RolesForm> rolesForms) {
		this.rolesForms = rolesForms;
	}

}
