package com.student.entities;
// Generated Jun 26, 2018 5:31:58 PM by Hibernate Tools 5.1.0.Alpha1

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Set;

/**
 * Module generated by hbm2java
 */

public class Module implements java.io.Serializable {
	DateFormat format = new SimpleDateFormat("dd/mm/yyyy", Locale.ENGLISH);
	private int id;
	private String name;
	private int users;
	private Date createdAt;
	private Date updatedAt;
	private Set<Form> forms = new HashSet<Form>(0);

	public Module() {
	}

	public Module(int id, String name, int users) {
		this.id = id;
		this.name = name;
		this.users = users;
	}
	
	
	@SuppressWarnings("rawtypes")
	public Module(Object object){
		LinkedHashMap objectMap = (LinkedHashMap)object;
		this.id = (int) objectMap.get("id");
		this.name = (String) objectMap.get("name");
		
		
		if (objectMap.get("createdAt")==null){
			this.createdAt=null;	
		}else{
			try{
				this.createdAt= (Date) format.parse(objectMap.get("createdAt").toString());	
			}catch(Exception exception){
				System.out.println("Error to convert createdAt in users.");
			}
		}
		
		if (objectMap.get("updatedAt")==null){
			this.updatedAt=null;	
		}else{
			try{
				this.updatedAt= (Date) format.parse(objectMap.get("createdAt").toString());
			}catch(Exception exception){
				System.out.println("Error to convert updatedAt in users");
			}
		}
}

	public Module(int id, String name, int users, Date createdAt, Date updatedAt, Set<Form> forms) {
		this.id = id;
		this.name = name;
		this.users = users;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.forms = forms;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getUsers() {
		return this.users;
	}

	public void setUsers(int users) {
		this.users = users;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}


	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set<Form> getForms() {
		return this.forms;
	}

	public void setForms(Set<Form> forms) {
		this.forms = forms;
	}

}
