package com.student.entities;
// Generated Jun 20, 2018 1:22:39 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
 

/**
 * QuizDetail generated by hbm2java
 */
 
public class QuizDetail implements java.io.Serializable {

	private int id;
	private Quiz quiz;
	private Student student;
	private Integer point;
	private Date createdAt;
	private Date updatedAt;

	public QuizDetail() {
	}

	public QuizDetail(int id, Quiz quiz, Student student) {
		this.id = id;
		this.quiz = quiz;
		this.student = student;
	}

	public QuizDetail(int id, Quiz quiz, Student student, Integer point, Date createdAt, Date updatedAt) {
		this.id = id;
		this.quiz = quiz;
		this.student = student;
		this.point = point;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	 
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	 
	public Quiz getQuiz() {
		return this.quiz;
	}

	public void setQuiz(Quiz quiz) {
		this.quiz = quiz;
	}

 
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	 
	public Integer getPoint() {
		return this.point;
	}

	public void setPoint(Integer point) {
		this.point = point;
	}

	 
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	 
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
