package com.student.entities;
// Generated Jun 20, 2018 1:22:39 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set; 

/**
 * Quiz generated by hbm2java
 */
 
public class Quiz implements java.io.Serializable {

	private int id;
	private Teacher teacher;
	private String name;
	private String code;
	private Date createdAt;
	private Date updatedAt;
	private Set<QuizDetail> quizDetails = new HashSet<QuizDetail>(0);

	public Quiz() {
	}

	public Quiz(int id, Teacher teacher, String name, String code) {
		this.id = id;
		this.teacher = teacher;
		this.name = name;
		this.code = code;
	}

	public Quiz(int id, Teacher teacher, String name, String code, Date createdAt, Date updatedAt,
			Set<QuizDetail> quizDetails) {
		this.id = id;
		this.teacher = teacher;
		this.name = name;
		this.code = code;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.quizDetails = quizDetails;
	}

	 
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	 
	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	 
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	
	public Set<QuizDetail> getQuizDetails() {
		return this.quizDetails;
	}

	public void setQuizDetails(Set<QuizDetail> quizDetails) {
		this.quizDetails = quizDetails;
	}

}
