package com.student.entities;
// Generated Jun 20, 2018 1:22:39 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
 
/**
 * Student generated by hbm2java
 */

public class Student implements java.io.Serializable {

	private int id;
	private String firstName;
	private String lastName;
	private String carne;
	private Date createdAt;
	private Date updatedAt;
	private Set<QuizDetail> quizDetails = new HashSet<QuizDetail>(0);

	public Student() {
	}

	public Student(int id, String firstName, String lastName, String carne) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.carne = carne;
	}

	public Student(int id, String firstName, String lastName, String carne, Date createdAt, Date updatedAt,
			Set<QuizDetail> quizDetails) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.carne = carne;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.quizDetails = quizDetails;
	}


	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	
	public String getCarne() {
		return this.carne;
	}

	public void setCarne(String carne) {
		this.carne = carne;
	}

	
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	
	public Set<QuizDetail> getQuizDetails() {
		return this.quizDetails;
	}

	public void setQuizDetails(Set<QuizDetail> quizDetails) {
		this.quizDetails = quizDetails;
	}

}
