package com.student.entities;
// Generated Jun 26, 2018 9:30:40 AM by Hibernate Tools 5.1.0.Alpha1

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Locale;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {
	DateFormat format = new SimpleDateFormat("dd/mm/yyyy", Locale.ENGLISH);
	private int id;
	private String name;
	private String password;
	private Date createdAt;
	private Date updatedAt;

	
	public Users() {
	}

	@SuppressWarnings("rawtypes")
	public Users(Object object){
		LinkedHashMap objectMap = (LinkedHashMap)object;
		this.id = (int) objectMap.get("id");
		this.name = (String) objectMap.get("name");
		this.password = (String) objectMap.get("password");
		
		if (objectMap.get("createdAt")==null){
			this.createdAt=null;	
		}else{
			try{
				this.createdAt= (Date) format.parse(objectMap.get("createdAt").toString());	
			}catch(Exception exception){
				System.out.println("Error to convert createdAt in users.");
			}
			
		}
		
		if (objectMap.get("updatedAt")==null){
			this.updatedAt=null;	
		}else{
			try{
				this.updatedAt= (Date) format.parse(objectMap.get("createdAt").toString());
			}catch(Exception exception){
				System.out.println("Error to convert updatedAt in users");
			}
		}
	}
	
	public Users(int id, String name, String password) {
		try{
			this.id = id;
			this.name = name;
			this.password = password;	
		}catch(Exception exception){
			System.out.println("error to cast User "+exception.getMessage());
		}
		
	}

	public Users(int id, String name, String password, Date createdAt, Date updatedAt) {
		try{
			this.id = id;
			this.name = name;
			this.password = password;
			this.createdAt = createdAt;
			this.updatedAt = updatedAt;	
		}catch(Exception exception){
			System.out.println("error to cast User "+exception.getMessage());
		}
		
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	 
}
