package com.student.entities;
// Generated Jun 26, 2018 4:22:06 PM by Hibernate Tools 5.1.0.Alpha1

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;


/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {
	DateFormat format = new SimpleDateFormat("dd/mm/yyyy", Locale.ENGLISH);
	private int id;
	private Roles roles;
	private String name;
	private String email;
	private String password;
	private Boolean isEnabled;
	private int users;
	private Date createdAt;
	private Date updatedAt;

	public Users() {
	}
	@SuppressWarnings("rawtypes")
	public Users(Object object){
		LinkedHashMap objectMap = (LinkedHashMap)object;
		this.id = (int) objectMap.get("id");
		this.name = (String) objectMap.get("name");
		this.password = (String) objectMap.get("password");
		this.isEnabled=(Boolean) objectMap.get("isEnabled");

		try{
			this.roles = new Roles(objectMap.get("roles"));	
		}catch(Exception exception){
			System.out.println("Error to convert roles");
		}
		
		
		if (objectMap.get("createdAt")==null){
			this.createdAt=null;	
		}else{
			try{
				this.createdAt= (Date) format.parse(objectMap.get("createdAt").toString());	
			}catch(Exception exception){
				System.out.println("Error to convert createdAt in users.");
			}
		}
		
		if (objectMap.get("updatedAt")==null){
			this.updatedAt=null;	
		}else{
			try{
				this.updatedAt= (Date) format.parse(objectMap.get("createdAt").toString());
			}catch(Exception exception){
				System.out.println("Error to convert updatedAt in users");
			}
		}
	}
	
	public Users(int id, Roles roles, String name, String email, String password, int users) {
		this.id = id;
		this.roles = roles;
		this.name = name;
		this.email = email;
		this.password = password;
		this.users = users;
	}

	public Users(int id, Roles roles, String name, String email, String password, Boolean isEnabled, int users,
			Date createdAt, Date updatedAt) {
		this.id = id;
		this.roles = roles;
		this.name = name;
		this.email = email;
		this.password = password;
		this.isEnabled = isEnabled;
		this.users = users;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Roles getRoles() {
		return this.roles;
	}
	
	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Boolean getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

	public int getUsers() {
		return this.users;
	}

	public void setUsers(int users) {
		this.users = users;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}
